-- AlterTable
ALTER TABLE `ExerciseStaging` MODIFY `status` ENUM('PENDING', 'APPROVED', 'REJECTED', 'APPLIED') NOT NULL DEFAULT 'PENDING';

-- AlterTable
ALTER TABLE `HealthProfileStaging` MODIFY `status` ENUM('PENDING', 'APPROVED', 'REJECTED', 'APPLIED') NOT NULL DEFAULT 'PENDING';

-- AlterTable
ALTER TABLE `NutritionStaging` MODIFY `status` ENUM('PENDING', 'APPROVED', 'REJECTED', 'APPLIED') NOT NULL DEFAULT 'PENDING';
