export enum ROUTES {
  AUTH = 'auth',
  ETL = 'etl',
  USERS = 'users',
  ROLES = 'roles',
  ORGANIZATIONS = 'organizations',
  EXERCISE = 'exercise',
  NUTRITION = 'nutrition',
  PLAN = 'plan',
  SESSION_EXERCISE = 'session-exercise',
  SESSION = 'session',
  HEALTH_PROFILE = 'health-profile',
  SUBSCRIPTION = 'subscription',
  DASHBOARD = 'dashboard',
}

export enum SERVICES {
  AUTH = 'AUTH_SERVICE',
  USERS = 'USERS_SERVICE',
  ROLES = 'ROLES_SERVICE',
  ORGANIZATIONS = 'ORGANIZATIONS_SERVICE',
  EXERCISE = 'EXERCISE_SERVICE',
  NUTRITION = 'NUTRITION_SERVICE',
  PLAN = 'PLAN_SERVICE',
  SESSION_EXERCISE = 'SESSION_EXERCISE_SERVICE',
  SESSION = 'SESSION_SERVICE',
  HEALTH_PROFILE = 'HEALTH_PROFILE',
  SUBSCRIPTION = 'SUBSCRIPTION_SERVICE',
}
