export enum ROUTES {
    AUTH = 'auth',
    USERS = "users",
    ORGANIZATIONS = 'organizations',
    EXERCISE = 'exercise',
    NUTRITION = 'nutrition',
    PLAN = 'plan',
    EXERCISE_LOG = 'exercise_log',
    WORKOUT_SESSION = 'WORKOUT_SESSION_SERVICE',
}

export enum SERVICES {
    AUTH = 'AUTH_SERVICE',
    USERS = 'USERS_SERVICE',
    ORGANIZATIONS = 'ORGANIZATIONS_SERVICE',
    EXERCISE = 'EXERCISE_SERVICE',
    NUTRITION = 'NUTRITION_SERVICE',
    PLAN = 'PLAN_SERVICE',
    EXERCISE_LOG = 'EXERCISELOG_SERVICE',
    WORKOUT_SESSION = 'WORKOUT_SESSION_SERVICE',
}
