export enum ROUTES {
  AUTH = 'auth',
  ETL = 'etl',
  USERS = 'users',
  ROLES = 'roles',
  ANALYTICS = 'analytics',
  ORGANIZATIONS = 'organizations',
  EXERCISE = 'exercise',
  NUTRITION = 'nutrition',
  PLAN = 'plan',
  SESSION_EXERCISE = 'session-exercise',
  SESSION = 'session',
  HEALTH_PROFILE = 'health-profile',
  SUBSCRIPTION = 'subscription',
  DASHBOARD = 'dashboard',
  POST = 'posts',
}

export enum SERVICES {
  AUTH = 'AUTH_SERVICE',
  USERS = 'USERS_SERVICE',
  ROLES = 'ROLES_SERVICE',
  ANALYTICS = 'ANALYTICS_SERVICE',
  API_METRICS = 'APIMETRICS_SERVICE',
  API_LOGS = 'APILOGS_SERVICE',
  MACHINE_STATS = 'MACHINESTATS_SERVICE',
  ORGANIZATIONS = 'ORGANIZATIONS_SERVICE',
  EXERCISE = 'EXERCISE_SERVICE',
  NUTRITION = 'NUTRITION_SERVICE',
  PLAN = 'PLAN_SERVICE',
  SESSION_EXERCISE = 'SESSION_EXERCISE_SERVICE',
  SESSION = 'SESSION_SERVICE',
  HEALTH_PROFILE = 'HEALTH_PROFILE',
  SUBSCRIPTION = 'SUBSCRIPTION_SERVICE',
  POST = 'POST_SERVICE',
}

export const ACTIVE_SUBSCRIPTION_STATUSES: string[] = [
  'ACTIVE',
  'active',
  'true',
];
